# -*- coffee -*- -p
author: YC <yinso.chen@gmail.com>
name: easydbi-repl
description: A simple repl for easydbi
version: 0.1.0
repository:
  type: git
  url: git://github.com/yinso/easydbi-repl.git
main: ./lib/main
bin:
  easydbi: ./bin/repl
engines:
  node: '>= 0.8.4'
scripts:
  test: make test
  prepublish: make
dependencies:
  underscore: =1.7.0
  loglet: '>=0.1.0'
  coffee-script: =1.8.0
  filelet: '>=0.1.0'
  funclet: '>=0.1.1'
  yargs: =1.3.3
  easydbi: '>=0.1.2'
  coffee-bean: '>=0.3.0'
  pegjs: =0.8.0
devDependencies:
  testlet: '>= 0.2.0'
