// Generated by CoffeeScript 1.4.0
(function() {
  var DBI, Runtime, fs, funclet, loglet, path, _;

  loglet = require('loglet');

  funclet = require('funclet');

  DBI = require('easydbi');

  require('easydbi-pg');

  path = require('path');

  fs = require('fs');

  funclet = require('funclet');

  _ = require('underscore');

  Runtime = (function() {

    function Runtime() {
      this.conns = {};
    }

    Runtime.prototype.connect = function(key, cb) {
      var _this = this;
      if (this.conns.hasOwnProperty(key)) {
        return cb(null);
      } else {
        return DBI.connect(key, function(err, conn) {
          if (err) {
            return cb(err);
          } else {
            _this.conns[key] = conn;
            _this.current = conn;
            return cb(null);
          }
        });
      }
    };

    Runtime.prototype["eval"] = function(cmd, cb) {
      if (!this.current) {
        return cb({
          error: 'no_connection_selected',
          description: 'use :show setups to see the connections or :setup to setup one up.'
        });
      } else {
        return this.current.query(cmd, {}, function(err, rows) {
          if (err) {
            return cb(err);
          } else {
            return cb(null, rows);
          }
        });
      }
    };

    Runtime.prototype.loadScript = function(filePath, cb) {
      var _this = this;
      return fs.readFile(filePath, 'utf8', function(err, data) {
        var item, queries;
        if (err) {
          return cb(err);
        } else {
          queries = _.filter((function() {
            var _i, _len, _ref, _results;
            _ref = data.split(/;/);
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              item = _ref[_i];
              _results.push(item.trim());
            }
            return _results;
          })(), function(q) {
            return (q != null ? q.length : void 0) > 0;
          });
          return funclet.eachSeries(queries, function(query, next) {
            loglet.log(query);
            return _this["eval"](query, function(err, rows) {
              if (err) {
                return next(err);
              } else {
                if (rows) {
                  loglet.log(rows);
                }
                return next(null);
              }
            });
          })["catch"](function(err) {
            return cb(err);
          }).done(function() {
            return cb(null);
          });
        }
      });
    };

    Runtime.prototype.exit = function(cb) {
      var conns, key, val, _ref;
      conns = [];
      _ref = this.conns;
      for (key in _ref) {
        val = _ref[key];
        conns.push(val);
      }
      return funclet.each(conns, function(conn, next) {
        return conn.disconnect(next);
      })["catch"](function(err) {
        return cb(err);
      }).done(function() {
        loglet.log('all connect disconnected.');
        return cb(null);
      });
    };

    return Runtime;

  })();

  module.exports = Runtime;

}).call(this);
