// Generated by CoffeeScript 1.4.0

/*

idea is simple - 
1) we can use the REPL to modify the database, which will be logged into a script.

This will be similar to history - but it will track only the particular ones that we want to store... 

Because this is a deployment script - we will want to store it at a place that we can gain access more easily.

We will also want the ability to change the particular database that it's stored to... 

>
*/


(function() {
  var Version, filelet, fs, funclet, loglet, path, _;

  filelet = require('filelet');

  fs = require('fs');

  path = require('path');

  funclet = require('funclet');

  _ = require('underscore');

  loglet = require('loglet');

  Version = (function() {

    Version.defaultPath = function() {
      return path.join(process.env.HOME, '.easydbi/history.json');
    };

    Version.make = function(filePath) {
      if (filePath == null) {
        filePath = this.defaultPath();
      }
      return new this(filePath);
    };

    function Version(filePath) {
      this.filePath = filePath;
      this.inner = [];
    }

    Version.prototype.bind = function(repl) {
      repl.rli.history = [].concat(this.inner).reverse();
      return repl.rli.historyIndex = 0;
    };

    Version.prototype.load = function(cb) {
      var _this = this;
      return funclet.bind(fs.readFile, this.filePath, 'utf8').then(function(data, next) {
        var args;
        try {
          args = JSON.parse(data);
          return next(null, args);
        } catch (e) {
          return next(e);
        }
      })["catch"](function(err) {
        _this.inner = [];
        return cb(null);
      }).done(function(args) {
        _this.inner = args;
        return cb(null);
      });
    };

    Version.prototype.save = function(cb) {
      var _this = this;
      return funclet.start(function(next) {
        return filelet.mkdirp(path.dirname(_this.filePath), next);
      }).then(function(next) {
        return fs.writeFile(_this.filePath, JSON.stringify(_this.inner), next);
      })["catch"](function(err) {
        loglet.error(err);
        return cb(null);
      }).done(function() {
        return cb(null);
      });
    };

    Version.prototype.log = function(cmd) {
      if (!_.contains(this.inner, cmd)) {
        return this.inner.push(cmd);
      }
    };

    return Version;

  })();

  module.exports = History;

}).call(this);
